trigger:
 - main 

schedules: 

 - cron: "0 0 * * *" 

   displayName: Daily midnight build 

   branches: 

     include: 
       - main 

   always: true 

pool: 

 vmImage: "ubuntu-latest" 

steps:
 - task: UsePythonVersion@0
   inputs:
     versionSpec: '3.10'
   architecture: 'x64'

 - bash: |
     pip install -r llama-requirements.txt

   displayName: install the necessary packages
   workingDirectory: $(Build.SourcesDirectory)

 - bash: |
     echo Authenticate with Huggingface repository 

     huggingface-cli login --token $(hf_token)

   displayName: "Authentication to Huggingface repo" 


 - script: | 

     python $(Build.SourcesDirectory)/llama_model_builder.py --model_name '${{ parameters.model_name }}'

   displayName: "Convert Huggingface model to ONNX model"
     
   workingDirectory: $(Build.BinariesDirectory)